spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: your_jwt_secret_key
  access-token-expiration: 600000       # 10?
  refresh-token-expiration: 1209600000  # 14?

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com.example: DEBUG
